imports:
    - { resource: parameters_local.yml }

parameters:
    locale: en

framework:
    secret:          "%secret%"
    default_locale:  "%locale%"

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
